url: https://paoderdoktor.github.io
repository: paoderdoktor/bloody-site

plugins:
    - jekyll-multiple-languages-plugin
    - jekyll-remote-theme

languages: ["fr", "en"]
exclude_from_localizations: ["assets"]
default_locale_in_subfolder: true
