url: https://paoderdoktor.github.io
repository: paoderdoktor/bloody-site
description: "yo."

remote_theme: pages-themes/cayman@v0.2.0

plugins:
    - jekyll-multiple-languages-plugin
    - jekyll-remote-theme

github: [metadata]

languages: ["fr", "en"]
#exclude_from_localizations: ["assets"]
#default_locale_in_subfolder: true
